language:
  - cpp

compiler:
  - gcc

install:
  - git clone https://github.com/jayrambhia/Install-OpenCV
  - cd Install-OpenCV/Ubuntu
  - ./opencv_latest.sh
  - sh install_cvBlob.sh

script:
  - cd CppAppOpenCV
  - make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf